# Generated by Django 2.2.5 on 2019-09-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='img'),
        ),
    ]
