# Generated by Django 2.2.5 on 2019-09-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboardapp', '0003_auto_20190922_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
